// GENERATED BY textFileToGoConst
// GitHub:     github.com/logrusorgru/textFileToGoConst
// input file: assert.lua
// generated:  Fri Nov 11 12:44:59 PST 2022

package tests

const lua_assert = `local assertions = require 'assertions'
local orig_assert = assert
return assertions:new {
    call = orig_assert,
}
`
