// GENERATED BY textFileToGoConst
// GitHub:     github.com/logrusorgru/textFileToGoConst
// input file: assert.lua
// generated:  Wed Nov 16 13:31:38 PST 2022

package tests

const lua_assert = `local assertions = require 'assertions'
local orig_assert = assert
return assertions:new {
    call = orig_assert,
}
`
